export const ROLE_GROUPS: { label: string; items: string[] }[] = [
  {
    label: "Marketing & growth",
    items: [
      "Marketing Manager",
      "Growth Hacker",
      "Growth Marketing",
      "Responsable Marketing",
      "Chef de projet marketing",
      "Traffic Manager",
      "SEO Manager",
      "SEA Manager",
      "Brand Manager",
      "Content Manager",
      "Inbound Marketing",
      "Email Marketing",
      "Performance Marketing",
      "Marketing Digital",
    ],
  },
  {
    label: "Communication",
    items: [
      "Chargé de communication",
      "Responsable communication",
      "Community Manager",
      "Social Media Manager",
      "Relations Presse",
      "Attaché de presse",
      "Communication Interne",
      "Porte-parole",
      "Chargé de relations publiques",
    ],
  },
  {
    label: "Product & tech",
    items: [
      "Product Manager",
      "Product Owner",
      "Chef de projet digital",
      "Product Designer",
      "Head of Product",
      "Data Product Manager",
      "Technical Product Manager",
      "Chef de projet SI",
      "MOA",
      "MOE",
      "Scrum Master",
      "Agile Coach",
    ],
  },
  {
    label: "Sales & business",
    items: [
      "Business Developer",
      "Sales Manager",
      "Customer Success",
      "Account Manager",
      "Account Executive",
      "Sales Representative",
      "Responsable commercial",
      "Ingénieur commercial",
      "Key Account Manager",
      "Head of Sales",
      "Inside Sales",
      "SDR",
      "BDR",
      "VP Sales",
      "Chargé d'affaires",
    ],
  },
  {
    label: "Ops & supply chain",
    items: [
      "Operations Manager",
      "Chief of Staff",
      "Responsable des opérations",
      "Supply Chain Manager",
      "Logistique",
      "Responsable logistique",
      "Acheteur",
      "Category Manager",
      "Procurement Manager",
      "Lean Manager",
      "Responsable production",
      "Directeur des opérations",
    ],
  },
  {
    label: "RH & recrutement",
    items: [
      "HR Manager",
      "Chargé de recrutement",
      "Talent Acquisition",
      "RRH",
      "DRH",
      "HRBP",
      "Responsable formation",
      "Gestionnaire paie",
      "HR Business Partner",
      "People Operations",
      "Culture & Engagement",
      "Responsable SIRH",
    ],
  },
  {
    label: "Finance & contrôle",
    items: [
      "Contrôleur de gestion",
      "Business Analyst",
      "Analyste financier",
      "DAF",
      "Directeur financier",
      "RAF",
      "Responsable comptable",
      "Auditeur",
      "Trésorier",
      "M&A Analyst",
      "Financial Controller",
      "FP&A Manager",
    ],
  },
  {
    label: "Conseil & stratégie",
    items: [
      "Consultant",
      "Strategy Manager",
      "Senior Consultant",
      "Manager conseil",
      "Directeur de mission",
      "Analyste stratégique",
      "Transformation Manager",
      "Change Management",
      "Management Consultant",
    ],
  },
  {
    label: "Créatif & design",
    items: [
      "UX Designer",
      "UI Designer",
      "Product Designer",
      "Graphiste",
      "Directeur artistique",
      "Motion Designer",
      "Rédacteur web",
      "Copywriter",
      "Designer graphique",
      "Web Designer",
      "Art Director",
      "Brand Designer",
    ],
  },
  {
    label: "Tech & data",
    items: [
      "Développeur Full Stack",
      "Développeur Front-end",
      "Développeur Back-end",
      "Data Analyst",
      "Data Scientist",
      "Data Engineer",
      "Machine Learning Engineer",
      "DevOps",
      "Cloud Architect",
      "CTO",
      "Lead Developer",
      "Software Engineer",
      "Solutions Architect",
      "Ingénieur IA",
    ],
  },
  {
    label: "Direction générale",
    items: [
      "CEO",
      "COO",
      "Directeur général",
      "Directeur de BU",
      "Head of",
      "VP",
      "Associate Director",
      "Managing Director",
    ],
  },
  {
    label: "Juridique",
    items: [
      "Juriste",
      "Juriste d'entreprise",
      "Avocat",
      "Juriste droit social",
      "Juriste droit des affaires",
      "Compliance Officer",
      "DPO",
      "Fiscaliste",
      "Notaire",
      "Paralegal",
      "Assistant juridique",
      "Legal Counsel",
      "Directeur juridique",
    ],
  },
  {
    label: "Comptabilité & gestion",
    items: [
      "Comptable",
      "Comptable unique",
      "Expert-comptable",
      "Chef comptable",
      "Assistant comptable",
      "Gestionnaire de paie",
      "Contrôleur financier",
      "Aide comptable",
      "Collaborateur comptable",
      "Responsable administratif et financier",
    ],
  },
  {
    label: "Santé & médical",
    items: [
      "Infirmier",
      "Aide-soignant",
      "Médecin",
      "Médecin généraliste",
      "Kinésithérapeute",
      "Pharmacien",
      "Préparateur en pharmacie",
      "Sage-femme",
      "Psychologue",
      "Dentiste",
      "Orthophoniste",
      "Diététicien",
      "Auxiliaire de puériculture",
      "Ergothérapeute",
    ],
  },
  {
    label: "Social & médico-social",
    items: [
      "Éducateur spécialisé",
      "Assistant social",
      "Auxiliaire de vie",
      "Aide à domicile",
      "Animateur socioculturel",
      "Conseiller en insertion",
      "Moniteur éducateur",
      "Accompagnant éducatif et social",
    ],
  },
  {
    label: "Éducation & formation",
    items: [
      "Professeur",
      "Enseignant",
      "Formateur",
      "Professeur des écoles",
      "Éducateur",
      "Animateur",
      "Assistant d'éducation",
      "Ingénieur pédagogique",
      "Responsable formation",
      "Accompagnateur scolaire",
    ],
  },
  {
    label: "Ingénierie & industrie",
    items: [
      "Ingénieur",
      "Ingénieur mécanique",
      "Ingénieur électrique",
      "Ingénieur qualité",
      "Ingénieur méthodes",
      "Ingénieur R&D",
      "Technicien de maintenance",
      "Chef de projet industriel",
      "Responsable qualité",
      "Dessinateur projeteur",
      "Automaticien",
      "Technicien bureau d'études",
    ],
  },
  {
    label: "Bâtiment & construction",
    items: [
      "Conducteur de travaux",
      "Chef de chantier",
      "Ingénieur BTP",
      "Architecte",
      "Économiste de la construction",
      "Maçon",
      "Électricien",
      "Plombier",
      "Chauffagiste",
      "Dessinateur BTP",
      "Métreur",
      "Coordinateur travaux",
    ],
  },
  {
    label: "Commerce & retail",
    items: [
      "Vendeur",
      "Conseiller de vente",
      "Responsable de magasin",
      "Chef de rayon",
      "Manager de rayon",
      "Directeur de magasin",
      "Employé libre-service",
      "Merchandiser",
      "Category Manager",
      "Animateur des ventes",
    ],
  },
  {
    label: "Relation client & support",
    items: [
      "Conseiller clientèle",
      "Chargé de clientèle",
      "Téléconseiller",
      "Customer Support",
      "Support technique",
      "Responsable service client",
      "Gestionnaire de contrats",
      "Chargé d'accueil",
    ],
  },
  {
    label: "Hôtellerie & restauration",
    items: [
      "Cuisinier",
      "Chef de cuisine",
      "Serveur",
      "Réceptionniste",
      "Barman",
      "Chef de rang",
      "Commis de cuisine",
      "Responsable de salle",
      "Directeur d'hôtel",
      "Gouvernante",
    ],
  },
  {
    label: "Transport & logistique",
    items: [
      "Chauffeur",
      "Chauffeur poids lourd",
      "Cariste",
      "Préparateur de commandes",
      "Magasinier",
      "Agent logistique",
      "Coordinateur transport",
      "Responsable entrepôt",
      "Affréteur",
    ],
  },
  {
    label: "Immobilier",
    items: [
      "Agent immobilier",
      "Négociateur immobilier",
      "Conseiller immobilier",
      "Gestionnaire locatif",
      "Property Manager",
      "Chargé de gestion locative",
      "Syndic de copropriété",
      "Expert immobilier",
    ],
  },
  {
    label: "Secteur public & associatif",
    items: [
      "Chargé de mission",
      "Attaché territorial",
      "Chef de projet public",
      "Responsable associatif",
      "Chargé de développement",
      "Coordinateur de projet",
      "Agent administratif",
      "Chargé de subventions",
    ],
  },
  {
    label: "Sciences & R&D",
    items: [
      "Chercheur",
      "Ingénieur de recherche",
      "Technicien de laboratoire",
      "Chef de projet R&D",
      "Chargé d'études",
      "Biologiste",
      "Chimiste",
      "Data Scientist",
    ],
  },
  {
    label: "Médias & édition",
    items: [
      "Journaliste",
      "Rédacteur",
      "Rédacteur en chef",
      "Chargé d'édition",
      "Community Manager",
      "Vidéaste",
      "Photographe",
      "Chargé de production",
    ],
  },
];

/** Domaines (niveau 1) → catégories ROLE_GROUPS (niveau 2) → postes (niveau 3). */
export const ROLE_DOMAINS: { label: string; groups: string[] }[] = [
  {
    label: "Marketing & com",
    groups: ["Marketing & growth", "Communication", "Médias & édition"],
  },
  {
    label: "Tech & produit",
    groups: ["Product & tech", "Tech & data", "Créatif & design", "Sciences & R&D"],
  },
  {
    label: "Business & vente",
    groups: [
      "Sales & business",
      "Conseil & stratégie",
      "Direction générale",
      "Commerce & retail",
      "Relation client & support",
    ],
  },
  {
    label: "Finance & admin",
    groups: ["Finance & contrôle", "Comptabilité & gestion", "Juridique", "RH & recrutement"],
  },
  {
    label: "Ops & terrain",
    groups: [
      "Ops & supply chain",
      "Ingénierie & industrie",
      "Bâtiment & construction",
      "Transport & logistique",
    ],
  },
  {
    label: "Santé & social",
    groups: ["Santé & médical", "Social & médico-social", "Éducation & formation"],
  },
  {
    label: "Services",
    groups: ["Hôtellerie & restauration", "Immobilier", "Secteur public & associatif"],
  },
];

export const LOCATION_SUGGESTIONS = ["Paris", "Lyon", "Remote", "Bordeaux", "Lille"];
export const LOCATION_RADIUS_OPTIONS = [
  { value: "city", label: "Intramuros", radiusKm: null },
  { value: "25", label: "25 km", radiusKm: 25 },
  { value: "50", label: "50 km", radiusKm: 50 },
  { value: "100", label: "100 km", radiusKm: 100 },
] as const;
export const CONTRACTS = ["CDI", "CDD", "Freelance", "Stage", "Alternance"];
export const REMOTE = ["Sur site", "Hybride", "Full remote"];
export const SALARY_QUICK_RANGES = ["30", "35", "40", "50", "60"] as const;

export const SECTOR_SUGGESTIONS = [
  "Culture & médias",
  "Spectacle & événementiel",
  "Tech & digital",
  "Santé & social",
  "Finance & assurance",
  "Public & administration",
  "Commerce & retail",
  "Industrie",
  "Éducation & formation",
  "Hôtellerie & tourisme",
  "Environnement & énergie",
  "Juridique",
  "Immobilier",
];

export type PreferencesForm = {
  target_roles: string[];
  target_sectors: string[];
  target_locations: string[];
  location_search_mode: "city" | "radius";
  location_radius_km: string;
  contract_type: string[];
  remote_pref: string[];
  salary_min: string;
  cv_url: string;
  cv_filename: string;
  letter_tone: string;
  letter_sample: string;
};

export const EMPTY_PREFERENCES: PreferencesForm = {
  target_roles: [],
  target_sectors: [],
  target_locations: [],
  location_search_mode: "city",
  location_radius_km: "",
  contract_type: [],
  remote_pref: [],
  salary_min: "",
  cv_url: "",
  cv_filename: "",
  letter_tone: "pro",
  letter_sample: "",
};

export function asStringArray(v: unknown): string[] {
  if (Array.isArray(v)) return v.filter((x): x is string => typeof x === "string");
  if (typeof v === "string" && v.trim()) return [v];
  return [];
}
